// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rpc

import (
	"sagebackend/internal/configs"
	"sagebackend/internal/core/services/countriessrv"
	"sagebackend/internal/core/services/currenciessrv"
	"sagebackend/internal/handlers/rpc/v1/countries"
	"sagebackend/internal/handlers/rpc/v1/currencies"
	"sagebackend/internal/repositories/pgdb/countriesrepo"
	"sagebackend/internal/repositories/pgdb/currenciesrepo"
)

// Injectors from wire.go:

func InitializeApp(appName configs.AppName, pgDbConfig configs.PgDbConfig, logConfig configs.LogConfig) (*app, error) {
	logger, err := NewLogger(appName, logConfig)
	if err != nil {
		return nil, err
	}
	db, err := NewPgDbInstance(pgDbConfig)
	if err != nil {
		return nil, err
	}
	database := NewGoquInstance(db)
	repository := currenciesrepo.New(logger, database)
	service := currenciessrv.New(logger, repository)
	handler := currencies.NewHandler(logger, service)
	countriesrepoRepository := countriesrepo.New(logger, database)
	countriessrvService := countriessrv.New(logger, countriesrepoRepository)
	countriesHandler := countries.NewHandler(logger, countriessrvService)
	server := NewGrpcServer(handler, countriesHandler)
	rpcApp := NewApp(server)
	return rpcApp, nil
}
